### ISSUE TITLE
#44 - Posts should be sorted by creation date with most recent on top

### ISSUE THREAD

**Issue by nswalters** [nss-evening-cohort-12/rare-rest-rare-api-arches#77]
- Sort the list by creation date with most recent on top

**Comment by nrg51098** [comment]
There is no creation date on the post, there is only publication date and I think we are already sorting the posts by publication date

**Comment by nrg51098** [comment]
If we really need to sort by most recent post first then inside the post model we need to change the publication date to datetimeField instead Datefield. would that be okay?
